//
//  PopularTVShowsInterfaces.swift
//  TVShows
//
//  Created by Vedran Burojevic on 06/05/16.
//  Copyright (c) 2016 1337code. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit
import RxSwift
import Result

// MARK: - Navigation -
enum  PopularTVShowsNavigationAction {
}

// MARK: - PopularTVShows Wireframe Interface -
protocol PopularTVShowsWireframeInterface: WireframeInterface {
    func performNavigationAction(action: PopularTVShowsNavigationAction)
    func configureModuleWith(viewController: PopularTVShowsViewController)
}

// MARK: - PopularTVShows View Interface -
protocol PopularTVShowsViewInterface: ViewInterface {
}

// MARK: - PopularTVShows View Presenter (Delegate) Interface -
protocol PopularTVShowsViewDelegateInterface: PresenterInterface {
    var loadingObservable: Observable<Bool> { get }
    var contentChangesObservable: Observable<[APITVShow]> { get }
    var errorObservable: Observable<(title: String, message: String)> { get }

    func didSelectNavigationAction(action: PopularTVShowsNavigationAction)

    func titleText() -> String
    func viewDidLoad()
}

// MARK: - PopularTVShows Interactor Interface -
protocol PopularTVShowsInteractorInterface: InteractorInterface {
    func loadPopularTVShows() -> Observable<Result<[APITVShow], NetworkingError>>
}
