//
//  PopularTVShowsWireframe.swift
//  TVShows
//
//  Created by Vedran Burojevic on 06/05/16.
//  Copyright (c) 2016 1337code. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

struct PopularTVShowsContext {
}

final class PopularTVShowsWireframe: NSObject {
    
    // MARK: - Private properties -
    private var _context: PopularTVShowsContext?
    private let _storyboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
    
    // MARK: - Public properties -
    weak var navigationController: UINavigationController?
    weak var viewController: UIViewController?
    
    // MARK: - Init -
    private override init() {}

    init(context: PopularTVShowsContext? = nil, navigationController: UINavigationController? = nil) {
        super.init()
        self._context = context
        self.navigationController = navigationController
    }
    
    // MARK: - Module setup -
    func instantiateAndConfigureModule() -> UIViewController {
        let moduleViewController = _storyboard.instantiateViewControllerWithIdentifier("PopularTVShowsViewController") as! PopularTVShowsViewController
        configureModuleWith(moduleViewController)
        viewController = moduleViewController
        return moduleViewController
    }
    
    func configureModuleWith(viewController: PopularTVShowsViewController) {
        let interactor = PopularTVShowsInteractor()
        let presenter = PopularTVShowsPresenter(wireframe: self, view: viewController, interactor: interactor)
        viewController.presenter = presenter
    }
}

// MARK: - PopularTVShows Wireframe Interface Requirements -
extension PopularTVShowsWireframe: PopularTVShowsWireframeInterface {
    
    func performNavigationAction(action: PopularTVShowsNavigationAction) {
        switch action {
        // #warning Implement actions 
        default:
            break
        }
    }
}